#!/bin/sh
set -e
rm -rf db/backups
rm -rf static/logs
mkdir -p static/logs
go clean
go build
zip -r -X crimson-arena.zip LICENSE README.md access_point_config.tar.gz crimson-arena db font schedules static switch_config.txt templates
mkdir -p build
rm -f build/crimson-arena
mv crimson-arena build/
