#!/bin/sh
set -e
ASSET_FILES="LICENSE README.md access_point_config.tar.gz fix_avatar_colors_for_overlay font schedules static switch_config.txt templates tunnel"

echo "Building Golden Arena for Linux x64..."
rm -rf golden-arena*
go clean
mkdir golden-arena
GOOS=linux GOARCH=amd64 go build -o golden-arena/
cp -r $ASSET_FILES golden-arena/
zip -r -X golden-arena.linux.x64.zip golden-arena

echo "Building Golden Arena for Linux ARM..."
rm -rf golden-arena/
go clean
mkdir golden-arena
GOOS=linux GOARCH=arm64 go build -o golden-arena/
cp -r $ASSET_FILES golden-arena/
zip -r -X golden-arena.linux.arm64.zip golden-arena

echo "Building Golden Arena for macOS Intel..."
rm -rf golden-arena/
go clean
mkdir golden-arena
GOOS=darwin GOARCH=amd64 go build -o golden-arena/
cp -r $ASSET_FILES golden-arena/
zip -r -X golden-arena.macos.x64.zip golden-arena

echo "Building Golden Arena for macOS M1..."
rm -rf golden-arena/
go clean
mkdir golden-arena
GOOS=darwin GOARCH=arm64 go build -o golden-arena/
cp -r $ASSET_FILES golden-arena/
zip -r -X golden-arena.macos.m1.zip golden-arena

echo "Building Golden Arena for Windows..."
rm -rf golden-arena/
go clean
mkdir golden-arena
GOOS=windows GOARCH=amd64 go build -o golden-arena/
cp -r $ASSET_FILES golden-arena/
zip -r -X golden-arena.windows.x64.zip golden-arena

echo "Cleaning up..."
rm -rf golden-arena/
go clean

echo "Done"